Fix compiler warning due to sign comparison
When compiling with -Werror, this causes the build to fail.

Warning was:

| yamux_frame.cpp:103:28: error: comparison of integers of different signs: 'gsl::span::index_type' (aka 'int') and 'const uint32_t' (aka 'const unsigned int') [-Werror,-Wsign-compare]
|     if (frame_bytes.size() < YamuxFrame::kHeaderLength) {
|         ~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~