Cross compiling fixes and improvements (#59)
* CMake: Expose CMake options to includes

This change shuffles the order of several CMake steps to expose CMake
options to included files.

By defining options before inclusion, included files are able to access
the input provided by the build system.

* CMake: Exclude test dependencies when building tests

* CMake: Allow build system to provide protobuf compiler

When building without Hunter, it is desirable to pass the path to protoc and
the protobuf include directory from the build system. Allow these variables
to be overridden.

Fixes the error:

| CMake Error at cmake/functions.cmake:52 (message):
|   Protobuf_PROTOC_EXECUTABLE is empty
| Call Stack (most recent call first):
|   cmake/functions.cmake:96 (compile_proto_to_cpp)
|   src/crypto/protobuf/CMakeLists.txt:6 (add_proto_library)

* Fix build error due to missing include

Error was:

| literals.cpp: In function 'libp2p::common::Hash256 libp2p::common::operator""_hash256(const char*, size_t)':
| literals.cpp:17:36: error: no matching function for call to 'min(size_t&, long unsigned int)'
|    17 |     std::copy_n(c, std::min(s, 32ul), hash.rbegin());
|       |                                    ^

* Fix build error due to mismatched types

Error was:

| literals.cpp: In function 'libp2p::common::Hash256 libp2p::common::operator""_hash256(const char*, size_t)':
| literals.cpp:19:36: error: no matching function for call to 'min(size_t&, long unsigned int)'
|    19 |     std::copy_n(c, std::min(s, 32ul), hash.rbegin());
|       |                                    ^

* Fix compiler warning due to sign comparison

When compiling with -Werror, this causes the build to fail.

Warning was:

| yamux_frame.cpp:103:28: error: comparison of integers of different signs: 'gsl::span::index_type' (aka 'int') and 'const uint32_t' (aka 'const unsigned int') [-Werror,-Wsign-compare]
|     if (frame_bytes.size() < YamuxFrame::kHeaderLength) {
|         ~~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~